name: Commit Message Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Commitlint
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
        with:
          config-file: .commitlintrc.yml
